version: '2'
volumes:
  data-magento: {}
  data-log: {}

networks:
  magento-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  web:
    container_name: web-node
    image : salle79/magento
    ports:
      - "80:80"
    networks:
      magento-network:
        ipv4_address: 10.5.0.5
    volumes:
      - ./www:/var/www/htdocs
    env_file:
      - env
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql-node
    image: mysql
    networks:
      magento-network:
        ipv4_address: 10.5.0.6
    env_file:
          - env
    volumes:
      - data-magento:/var/lib/mysql
      - data-log:/var/log
      - ./data/database.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis-node
    image: redis:latest
    networks:
      magento-network:
        ipv4_address: 10.5.0.8